name: CI pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout source code
          uses: actions/checkout@v5
        - name: set up nodejs
          uses: actions/setup-node@v3
          with:
              node-version: 16
        - name: install dependencies
          run: npm install
        - name: test
          run: npm test